# Generated by Django 2.2.13 on 2020-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team Lead', 'Team Lead'), ('Member', 'Member')], max_length=50, null=True),
        ),
    ]
