# Generated by Django 2.2.13 on 2020-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200629_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ManyToManyField(to='app.Profile'),
        ),
    ]
