# Generated by Django 2.2.13 on 2020-06-29 20:43

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200629_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ips',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
