# Generated by Django 2.2.13 on 2020-06-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200630_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='questo',
            new_name='_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Profile', to_field='questo'),
        ),
    ]
