# Generated by Django 2.2.13 on 2020-06-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200630_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
