# Generated by Django 2.2.13 on 2020-06-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200630_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='profile',
            new_name='_id',
        ),
    ]
