# Generated by Django 2.2.13 on 2020-06-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
