# Generated by Django 2.2.13 on 2020-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200701_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.CharField(choices=[('0', 'BUY'), ('1', 'SELL')], default=0, max_length=50),
        ),
    ]
