# Generated by Django 2.2.13 on 2020-07-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_order_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default=0, max_length=50),
        ),
    ]
