# Generated by Django 2.2.13 on 2020-07-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200702_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.Field(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='', max_length=50),
        ),
    ]
