# Generated by Django 2.2.13 on 2020-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20200702_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.Field(choices=[('NOT COMPLETED', 'NOT COMPLETED'), ('COMPLETED', 'COMPLETED')], default='', max_length=50),
        ),
    ]
