# Generated by Django 2.2.13 on 2020-07-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_order_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.Field(choices=[('COMPLETED', 'COMPLETED'), ('NOT COMPLETED', 'NOT COMPLETED')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.Field(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='', max_length=50),
        ),
    ]
