# Generated by Django 2.2.13 on 2020-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200703_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.Field(choices=[('NOT COMPLETED', 'NOT COMPLETED'), ('COMPLETED', 'COMPLETED')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.Field(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='', max_length=50),
        ),
    ]
