# Generated by Django 2.2.13 on 2020-07-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200703_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done',
            field=models.Field(choices=[('NOT COMPLETED', 'NOT COMPLETED'), ('COMPLETED', 'COMPLETED')], default='NOT COMPLETED', max_length=50),
        ),
    ]
