# Generated by Django 2.2.13 on 2020-07-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200703_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.Field(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
